import "package:drift/drift.dart";

/// drift tables for the offline-first data layer (flutter-plan §3.1, trimmed
/// to what WP2+WP5 need now: Farms, Batches, SeqCounters, Outbox, MetaKv).
///
/// Users/UserRoles/BatchEventsCache/InboxItems are intentionally deferred —
/// inbox and chain-of-custody stay API-backed this iteration.

/// Sync state shared by Farms and Batches rows.
///
/// LOCAL      — created on device, outbox entry still pending.
/// SYNCED     — confirmed by the server; server pulls may update the row.
/// ERROR      — server permanently rejected the push (4xx); UI surfaces it.
abstract class SyncStateColumns {
  static const local = "LOCAL";
  static const synced = "SYNCED";
  static const error = "ERROR";
}

/// Outbox entry statuses (flutter-plan §3.2).
abstract class OutboxStatus {
  static const pending = "PENDING";
  static const inFlight = "IN_FLIGHT";
  static const synced = "SYNCED";
  static const failedPermanent = "FAILED_PERMANENT";
}

@DataClassName("Farm")
class Farms extends Table {
  /// UUIDv7, client-generated so outbox payloads can reference the farm
  /// before the server knows about it.
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get areaCode => text()(); // 'GM','KN','MK'…
  TextColumn get farmerCode => text().nullable()(); // null until first sync
  RealColumn get sizeValue => real()();
  TextColumn get sizeUnit => text().withDefault(const Constant("ACRE"))();
  RealColumn get lat => real().nullable()();
  RealColumn get lng => real().nullable()();
  TextColumn get addressText => text().nullable()();
  TextColumn get locationPublicLevel =>
      text().withDefault(const Constant("DISTRICT"))();
  TextColumn get syncState => text().withDefault(const Constant("LOCAL"))();
  DateTimeColumn get createdAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName("Batch")
class Batches extends Table {
  /// UUIDv7, client-generated.
  TextColumn get id => text()();
  /// Unique locally too — catches same-device dupes; collisions with other
  /// devices surface as 409 BATCH_NO_TAKEN and are regenerated by the worker.
  TextColumn get batchNo => text().unique()();
  TextColumn get farmId => text()();
  TextColumn get harvestType => text()(); // 'T' | 'Q'
  TextColumn get harvestDate => text()(); // yyyy-MM-dd (API sends date string)
  IntColumn get treeCount => integer()();
  RealColumn get weightKg => real()();
  TextColumn get status => text().withDefault(const Constant("HARVESTED"))();
  TextColumn get currentHolderId => text().nullable()();
  TextColumn get currentHolderRole => text().nullable()();
  TextColumn get rootBatchNo => text()();
  TextColumn get stageSuffix => text().withDefault(const Constant(""))();
  TextColumn get syncState => text().withDefault(const Constant("LOCAL"))();
  DateTimeColumn get createdAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Per-farm daily SEQ allocation, keyed by (farmId, dayKey) where dayKey is
/// `<year>-<julianDay>` e.g. '2026-172'. One transaction allocates the seq,
/// generates the batch number and enqueues the outbox entry so they can never
/// diverge.
@DataClassName("SeqCounter")
class SeqCounters extends Table {
  TextColumn get farmId => text()();
  TextColumn get dayKey => text()();
  IntColumn get lastSeq => integer()();

  @override
  Set<Column> get primaryKey => {farmId, dayKey};
}

/// Queued mutations pushed by [SyncWorker] (flutter-plan §3.2).
@DataClassName("OutboxRow")
class Outbox extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get entityType => text()(); // farm | batch | transfer | accept
  TextColumn get entityId => text()(); // local UUIDv7 of the entity
  TextColumn get method => text()(); // POST
  TextColumn get path => text()(); // /farms, /batches …
  TextColumn get payloadJson => text()();
  /// uuid v4, stable per entry; rotated when a 409 regenerates the payload.
  TextColumn get idempotencyKey => text()();
  /// outbox.id of a prerequisite entry that must reach SYNCED first.
  IntColumn get dependsOn => integer().nullable()();
  TextColumn get status => text().withDefault(const Constant("PENDING"))();
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  IntColumn get regenCount => integer().withDefault(const Constant(0))();
  DateTimeColumn get nextRetryAt => dateTime().nullable()();
  TextColumn get lastErrorCode => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();
}

/// Small key/value store: cached user profile JSON, flags.
@DataClassName("MetaKvEntry")
class MetaKv extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column> get primaryKey => {key};
}
